config/routes.rb
Rails.application.routes.draw do
root :to=>"page#index"
resources :news
resources :witness
resources :about do
    collection do      
      get :history
      resources :members do
        collection do        
          get :pastor
          get :secretary
          get :officer
        end
      end
      resources :groups do
          collection do
            get :sunday_workship
            get :qt        
            get :family
            get :matins
            get :elder
            get :women
            get :married          
            get :youth
            get :young
            get :awana
            get :choir
            get :workship
        end
      end
    end
end
resources :admin do
  collection do
    post :login
    post :logout
    get :logout
  end
end
resources :goal do
  collection do
    get :ministry
    get :annual
    get :next
    get :midRange
  end
end
resources :location do
  collection do     
    get :b1
    get :floor1
    get :floor2
    get :floor4
    get :floor5
  end
end
 get "/qa" => "page#qa"
 get "/schedule" => "page#schedule"
 get "/contact" => "page#contact"
 post "uploader/image"=> "uploader#image"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
	validates_presence_of :title
	validates_presence_of :content
end

app/models/witness.rb
class Witness < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
  def floorplan

  end
  def location

  end
  def history

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
		@is_admin = to_bool(session[:is_admin])

	end
	def login
		admin = Admin.where(:account => 'admin').first()
		session[:is_admin] = admin.password == params[:password]
		redirect_to :action => :index
	end
	def logout
		session[:is_admin] = false
		redirect_to request.referer
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :init
  def init
    @is_admin = to_bool(session[:is_admin])
  end
  protected
  def to_bool(value)
    return true if value == true || value.to_s.strip =~ /^(true|yes|y|1)$/i
    return false
  end
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
  def ministry

  end
  def annual

  end
  def next

  end
  def midRanage

  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
end

app/controllers/location_controller.rb
class LocationController < ApplicationController

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def index
		@news_list = News.all
	end
	def new
		@news = News.new
	end
	def create
		@news = News.new(news_params)
		@news.save

		redirect_to :action => :index

	end
	def update
		@news = News.find(params[:id])
		@news.update(news_params)

		redirect_to :action => :show, :id => @news
	end
	def show
		@news = News.find(params[:id])
	end
	def edit
		@news = News.find(params[:id])
	end

	private

	def news_params
		params.require(:news).permit(:title, :content,:photo)		
	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def index
		
	end
	def about
		@aboutwhat=params[:what]
	end
	def mission
		
	end
	def witness

	end

	def schedule

	end
	def qa

	end
end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  def image
    photopath = save_photo
    render :text =>  "<script> parent.$('#preview').attr('src','" + photopath + "').show(); parent.$('#witness_photo').val('" + photopath + "');</script>"
  end

  def save_photo
    photoextname = File.extname(params['photo'].original_filename)
    photoname = Time.now.to_s(format = :number) + photoextname
    photodir = "#{photoname}"
    File.open("public/images/witness/#{photodir}", "wb") do |f|
      f.write(params['photo'].read)
    end
    return "/images/witness/#{photoname}"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def say
		
	end
end

app/controllers/witness_controller.rb
class WitnessController < ApplicationController
    def index
      #
      @witnesses = Witness.where(is_active: true).order(:created_at).reverse_order.take(10)

    end
    def new
      @witness = Witness.new
    end
    def create
      @witness = Witness.new(witness_params)
      @witness.save

      redirect_to :action => :index

    end
    def update
      @witness = Witness.find(params[:id])
      @witness.update(witness_params)
      redirect_to :action => :show, :id => @witness
    end
    def show
      @witness = Witness.find(params[:id])
    end
    def edit
      @witness = Witness.find(params[:id])
    end
    def destroy
      @witness = Witness.find(params[:id])
      @witness.update(is_active: false)
      redirect_to :action => :index
    end
    private
    def witness_params

      params.require(:witness).permit(:title, :content,:photo)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/witness_helper.rb
module WitnessHelper
end

app/views/about/_leftMenu.html.erb
<div class="col-md-2 sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">教會簡史</a></li>
    <li><a href="/about/history">教會簡史</a></li>
  </ul>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">同工介紹</a></li>
    <li><a href="/about/members/pastor">主任牧師</a></li>
    <li><a href="/about/members/secretary">幹事傳道</a></li>
    <li><a href="/about/members/officer">長執同工</a></li>
  </ul>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">各項聚會</a></li>
    <li><a href="/about/groups/sunday_workship">主日禮拜</a></li>
    <li><a href="/about/groups/qt">QT小組</a></li>
    <li><a href="/about/groups/family">家庭禮拜</a></li>
    <li><a href="/about/groups/matins">週間禱告會</a></li>
    <li><a href="/about/groups/elder">松年團契</a></li>
    <li><a href="/about/groups/married">伉儷團契</a></li>
    <li><a href="/about/groups/women">女宣團契</a></li>
    <li><a href="/about/groups/youth">社青團契</a></li>
    <li><a href="/about/groups/young">青少年團契</a></li>
    <li><a href="/about/groups/awana">AWANA兒童主日學</a></li>
    <li><a href="/about/groups/choir">聖歌隊</a></li>
    <li><a href="/about/groups/workship">敬拜團</a></li>
  </ul>
</div>

app/views/about/floorplan.html.erb
<h4>教會配置圖</h4>


<h3>【地下室】（多功能活動中心）</h3>
副堂、愛餐區、兒童遊戲區、卡拉ＯＫ區、角落咖啡區。
<img src="/images/floorplan/B1_0.jpg" alt="副堂"/>
<img src="/images/floorplan/B1_1.jpg" alt="兒童遊戲區"/>
<img src="/images/floorplan/B1_2.jpg" alt="愛餐區"/>
<img src="/images/floorplan/B1_3.jpg" alt="角落咖啡區"/>
<img src="/images/floorplan/B1_4.jpg" alt="卡拉ＯＫ區"/>
<h3>【一樓】</h3>
「幹事辦公事」、「愛心廚房」
<img src="/images/floorplan/F1.jpg" alt=""/>

<h3>【二樓】</h3>
「禮拜堂」、「交誼廳」、「行政辦公室」
<img src="/images/floorplan/2F_0.jpg" alt="愛餐區"/>
<img src="/images/floorplan/2F_1.jpg" alt="角落咖啡區"/>
<img src="/images/floorplan/2F_2.jpg" alt="卡拉ＯＫ區"/>
<h3>【四樓】（團契活動中心）</h3>
「團契聚會所」、「個人禱告室」、「練團室」、「會議室」、「檔案室」。
<img src="/images/floorplan/4F_0.jpg" alt="愛餐區"/>
<img src="/images/floorplan/4F_1.jpg" alt="角落咖啡區"/>

<h3>【五樓】（主日學兒童中心）</h3>
「主日學兒童中心」
<img src="/images/floorplan/5F_0.jpg" alt="愛餐區"/>
<img src="/images/floorplan/5F_1.jpg" alt="角落咖啡區"/>
<img src="/images/floorplan/5F_2.jpg" alt="卡拉ＯＫ區"/>

app/views/about/groups.html.erb
<h4>GROUPS PAGE</h4>

app/views/about/history.html.erb
<div class="container-fluid main-container">
  <%=render 'about/leftMenu' %>
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-heading">

      </div>
      <div class="panel-body">
        <h4>埔墘教會  簡史</h4>

        <p>1969年5月22日由李長裕牧師與梁文彬長老召集黃福田、陳定川、曾木卿、陳金樹、池善蒲等七人組成委員會。</p>

        <p>同年6月5日租用埔墘公寓41號為聚會地點，6月8日首次在該地點舉行禮拜，10月5日由台北中會議長主持開設典禮。</p>

        <p>1971年5月16日購得一座新建兩層樓房(中山路二段176巷22號)為禮拜堂，同年6月6日舉行主日禮拜及各項聚會。</p>

        <p>1973年1月7日選出首任長老3名，執事5名，並於2月12日昇格為堂會，4月8日舉行新堂奉獻典禮。</p>

        <p>由於信徒日漸增多，10餘坪之禮拜堂不夠容納，加上市場內買賣聲吵雜，嚴重干擾聚會，乃決議另購新堂，</p>

        <p>於1978年8月14日購得現址(板橋市三民路二段186巷2弄6號二、三、四樓及8號二樓，總坪數155.12坪)，</p>

        <p>同年10月28日啟用新禮拜堂，1980年10月25日舉行設教11週年暨聖殿奉獻典禮。</p>

        <p>全體信徒齊心協力推行聖工數十年，仍懷抱異象展望、不斷成長之心意，在空間已不敷使用與展望異象同時，</p>

        <p>於2014年1月承租本會現址一樓兩處(含地下室)共約120坪空間。</p>

        <p>並隨即積極投入及規劃，以五個多月的時間擴建、逐漸整建現有空間。</p>

        <p>同年6月8日聖靈降臨節，也是教會設教45週年，當天上午主日禮拜，</p>

        <p>眾信徒滿心喜悅以「設教四十五週年感恩禮拜」數算神的恩典，</p>

        <p>並於下午三點卅分舉行「多功能活動中心啟用感恩禮拜」領受上帝加倍豐盛的恩典。</p>
        <br />

        <h4>●.本堂歷任牧者</h4>

        <p>⊙ 第一任牧者：梁秀德牧師（1969年6月8日-1976年6月28日）</p>

        <p>  1973年4月8日舉行首任牧師就任授職暨新堂奉獻感恩禮拜。</p>
        <br />
        <p>⊙ 第二任牧者：黃思明牧師（1976年7月4日-1989年8月31日）</p>

        <p>  1976年8月29日舉行牧師就任授職感恩禮拜。</p>
        <br />
        <p>⊙ 第三任牧者：江永遠牧師（1990年7月30日-2005年2月13日）</p>

        <p>  1990年10月21日舉行牧師就任授職暨設教21週年感恩禮拜。</p>
        <br />
        <p>⊙ 第四任牧者：沈建議牧師（2006年6月10日-2011年9月30日）</p>

        <p>  2006年8月13日舉行封牧暨就任授職感恩禮拜。</p>
        <br />
        <p>⊙ 第五任牧者：劉世光牧師（2013年1月1日～迄今）</p>

        <p> 2013年1月20日舉行牧師就任授職感恩禮拜。</p>
        <br />
      </div>
    </div>
  </div>
</div>

app/views/about/index.html.erb
<h4>ABOUT PAGE</h4>

app/views/about/officer.html.erb
<div class="container-fluid main-container">
  <%=render 'about/leftMenu' %>
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-heading">

      </div>
      <div class="panel-body">
        敬請期待
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
Admin Login Status: <%=@is_admin %>

<% if @is_admin %>
    <%= form_tag('/admin/logout', method: "post") do %>
        <%= submit_tag("Logout") %>
    <% end %>
<% else %>
    <%= form_tag('/admin/login', method: "post") do %>
        <%= label_tag( "password:") %>
        <%= password_field_tag('password') %>
        <%= submit_tag("Login") %>
    <% end %>
<% end%>

app/views/goal/_leftMenu.html.erb
<div class="col-md-2 sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">異象與使命</a></li>
    <li><a href="/goal">異象與使命</a></li>
  </ul>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">年度目標</a></li>
    <li><a href="/goal/ministry">事工目標</a></li>
    <li><a href="/goal/annual">2014事工</a></li>
    <li><a href="/goal/next">2015事工</a></li>
    <li><a href="/goal/midRange">中程目標</a></li>
  </ul>
</div>

app/views/goal/annual.html.erb
<div class="container-fluid main-container">
  <%= render 'goal/leftMenu' %>
  <div class="col-md-10 content">
    <article class="panel panel-default">
      <header class="panel-heading">

      </header>
      <section class="panel-body">
        <h4>2014年度目標：「靈修」一領一，「生命」新倍加。</h4>
        <p>「但你所學習的，所確信的，要存在心裡；因為你知道是跟誰學的，</p>
        <p>並且知道你是從小明白聖經，這聖經能使你因信基督耶穌，有得救的智慧。</p>
        <p>聖經都是神所默示的，於教訓、督責、使人歸正、教導人學義都是有益的，</p>
        <p>叫屬神的人得以完全，預備行各樣的善事。」(提後三14-17)</p>
        <p>[目標]</p>
        <p>鼓勵信徒認識聖經和裝備領袖，並每日有固定的靈修生活，</p>
        <p>使屬靈生命得以成長。藉由提高信仰的素質，且著重信心的建立，靈命的塑造和生命的見証。</p>
        <img src="/images/goal/annual.jpg" alt="埔墘長老教會" class="content-img" />
        <p>[事工]</p>
        <ol>
          <li>全教會信徒每日靈修研讀。</li>
          <li>主日ＱＴ小組成立。</li>
          <li>小家關懷事工。</li>
          <li>AWANA兒童事工。</li>
        </ol>
      </section>
    </article>
  </div>
</div>

app/views/goal/index.html.erb
<div class="container-fluid main-container">
<%= render 'goal/leftMenu' %>
  <div class="col-md-10 content">
    <article class="panel panel-default">
      <header class="panel-heading">

      </header>
      <section class="panel-body">
      <h4>◎埔墘教會異象：一領一全人成長‧邁向50禧年</h4>
<p>在事工規劃中，以「一領一全人成長‧邁向設教50禧年」為教會異象。</p>
<p>此乃依循總會"一領一新倍加"宣教運動（One-leads-One, Doubling Movement，簡稱「新倍加運動」）的推動，</p>
<p>並依據約翰一書二12-13節信仰生命程度的劃分(小子、少年人、父老(註一）)，</p>
<p>以"一領一策略"及"生命成長五大向度（註二）"的事工推動，</p>
<p>藉以裝備信徒做主的門徒，逐年逐步地建造教會。</p>
<h4>
 ◎埔墘教會使命：
</h4>
<p>以一領一的策略，在板橋區建立一間敬拜上帝、實踐神愛的教會，</p>
<p>並裝備信徒做主的門徒，得以見證福音的大能。</p>
<p>成為不斷學習實踐大使命(太28:19-20)與大誡命(太22:36-40)的有異象、有熱情教會，</p>
<p>完成神向教會所命定的使命。</p>
<blockquote class="small">
<h5>註一：三個靈命程度（小子、少年人、父老）</h5>
<p>(約翰一書二12-13)小子們哪、我寫信給你們、因為你們的罪藉著主名得了赦免。</p>
<p>父老阿、我寫信給你們、因為你們認識那從起初原有的。</p>
<p>少年人哪、我寫信給你們、因為你們勝了那惡者。</p>
<p>小子們哪、我曾寫信給你們、因為你們認識父。</p>
  <ol>
    <li>小子(Children)：是初信主，經過初信栽培後的信徒。</li>
    <li>少年人(Young Men)：是信主日子尚淺，尚在靈裡成長中的信徒。</li>
    <li>父老(Father)：是信主日子較長，和在靈裡已經較成熟的徒。</li>
  </ol>
</p>

<h5>註二：五大成長向度</h5>
  <ol>
    <li>靈命成長</li>
    <li>關懷成長</li>
    <li>禱告成長</li>
    <li>敬拜成長</li>
    <li>佈道成長</li>
  </ol>
</blockquote>
<img src="/images/goal/mission.jpg" alt="埔墘長老教會" class="content-img" />
</section>
    </article>
  </div>
</div>

app/views/goal/midRange.html.erb
<div class="container-fluid main-container">
  <%= render 'goal/leftMenu' %>
  <div class="col-md-10 content">
    <article class="panel panel-default">
      <header class="panel-heading">

      </header>
      <section class="panel-body">
        <ul>
          <li>
            <h4>年度目標：「禱告」一領一，「見證」新倍加。</h4>
            <section>
              <p>「我勸你第一要為萬人懇求，禱告，代求，祝謝。」(提前二1)</p>
              <p>[目標]</p>
              <p>提昇信徒對禱告的認知與實踐，增設重要危急禱告事項的傳遞途徑，增加見証分享的機會，</p>
              <p>以體會禱告之果效。在團契、教會中，藉由操練各種不同禱告方式，彼此學習成為代禱守望者。</p>
            </section>
          </li>
          <li><h4>年度目標：「敬拜」一領一，「事奉」新倍加。</h4>
            <section>
              <p>「來啊，我們要屈身敬拜，在造我們的耶和華面前跪下。</p>
              <p>因為衪是我們的神；我們是衪草場的羊，是衪手下的民。惟願你們今天聽衪的話。」(詩95:6-7)</p>
              <p>[目標]</p>
              <p>帶領及教導會眾以心靈和真理進入敬拜(含傳統敬拜)，經歷神的臨在及作生命的敬拜。</p>
              <p>並訓練信徒，能藉著敬拜的恩賜操練，進而轉化生命並彰顯神榮耀。</p>
            </section>
          </li>
          <li>
            <h4>年度目標：「佈道」一領一，「信徒」新倍加。</h4>
            <section>
              <p>「然而人未曾信祂、怎能求祂呢．未曾聽見祂、怎能信祂呢．沒有傳道的、怎能聽見呢？</p>
              <p>若沒有奉差遣、怎能傳道呢？如經上所記：報福音傳喜信的人、他們的腳蹤何等佳美。」(羅10:14-15)</p>
              <p>[目標]</p>
              <p>透過本地多元化和社區適切性的事工與資源，建立有效且有充足裝備的福音隊工，</p>
              <p>在板橋廣傳福音，履行主耶穌所吩咐的大使命！</p>
            </section>
          </li>
        </ul>
      </section>
    </article>
  </div>
</div>

app/views/goal/ministry.html.erb
<div class="container-fluid main-container">
  <%= render 'goal/leftMenu' %>
  <div class="col-md-10 content">
    <article class="panel panel-default">
      <header class="panel-heading">

      </header>
      <section class="panel-body">
        <h4>◎埔墘教會事工目標：</h4>
        <p>落實「一領一全人成長；邁向50禧年」，透過下列事工來執行：</p>
        <p>分齡牧養、團契、小組的架構、目標導向的原則，</p>
        <p>依此做整體事工及生命建造程序的整合，以期能一步步實踐異象與目標。</p>
        <p>依信徒三種信仰生命屬靈程度(小子、少年人、父老)，</p>
        <p>在事工上予以五大成長向度的牧養(閱教會異象使命)，</p>
        <p>逐步從小子→少年人→父老，不斷成長成熟。</p>
      </section>
    </article>
  </div>
</div>

app/views/goal/next.html.erb
<div class="container-fluid main-container">
  <%= render 'goal/leftMenu' %>
  <div class="col-md-10 content">
    <article class="panel panel-default">
      <header class="panel-heading">

      </header>
      <section class="panel-body">
      	<h4>2015年度目標：「關懷」一領一，「愛心」新倍加。</h4>

        <p>「免得身上分門別類，總要肢體彼此相顧。若一個肢體受苦，所有的肢體就一同受苦；</p>
        <p>若一個肢體得榮耀，所有的肢體就一同快樂。」(林前十二25-26)</p>
        <p>[目標]</p>
        <p>加強信徒、團契、小組間的關懷，藉以彼此建立、關懷、勉勵，</p>
        <p>並加強對教會的關懷，以此關愛教會、熱愛靈魂，實踐彼此相愛的誡命。</p>
        <img src="/images/goal/next.jpg" alt="埔墘長老教會" class="content-img" />
        <p>[事工]</p>
        <ol>
          <li>每日QＴ事工。</li>
          <li>平信徒牧養行動。</li>
          <li>一對一陪讀課程。</li>
          <li>屬靈家長培訓。</li>
        </ol>
      </section>
    </article>
  </div>
</div>

app/views/groups/awana.html.erb
<div class="container-fluid main-container">
  <%=render 'about/leftMenu' %>
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-heading">

      </div>
      <div class="panel-body">
        <!-- todo carousel module start-->
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                <li data-target="#myCarousel" data-slide-to="2" class=""></li>
                <li data-target="#myCarousel" data-slide-to="3" class=""></li>
              </ol>
              <div class="carousel-inner" role="listbox">
                <div class="item active">
                  <img src="/images/about/groups/awana/1.jpg" >
                </div>
                <div class="item">
                  <img src="/images/about/groups/awana/2.jpg" >
                </div>
                <div class="item">
                  <img src="/images/about/groups/awana/3.jpg" >
                </div>
                <div class="item">
                  <img src="/images/about/groups/awana/4.jpg" >
                </div>
              </div>
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
        </div>
        <!-- todo carousel module end-->
        <p>ＡＷＡＮＡ兒童主日學：</p>
        <p>『耶穌說：讓小孩子到我這裡來，不要禁止他們；因為在神國的正是這樣的人。(太19:14)』</p>
        <p>本主日學以教導年幼至老年者，相信和接受耶穌基督為救主並裝備訓練成為健全的基督徒為宗旨。</p>
        <p>在這裡孩子可以學習交朋友、好習慣、好品格，學習聖經品格、參加團體遊戲、建造團隊精神。</p>
        <p>對象：幼稚園至國中</p>
        <p>內容：聖經信息、詩歌、手冊時間、AWANA遊戲</p>
        <p>時間：週日上午９：３０</p>
        <p>地點：教會５樓兒童活動中心</p>
        <p>[AWANA事工簡介]</p>
        <p>AWANA源自聖經「你當竭力，在神面前得蒙喜悅，作無愧的工人，按著正意分解真理的道。(提後2:15)」</p>
        <p>AWANA這個字來自Approved Workmen Are Not Ashamed（得蒙喜悅作無愧的工人）這幾個英文字的字首。</p>
        <p>目前全世界已有一百多個國家以awana事工，來為主造就及培訓兒童與青少年。</p>
        <p>埔墘教會AWANA事工特色如下：</p>
        <ol>
          <li>在聚會中導師與隊員都穿制服，增進歸屬及合一感。</li>
          <li>透過學習手冊及獎勵制度，激勵隊員，在學習神話語上所下的功夫。</li>
          <li>遊戲時間(Awana Game)每週推陳出新，兼具益智反應及體能運動，也增進孩童們的運動技能及彼此激勵的團隊精神。</li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/location/_leftMenu.html.erb
<div class="col-md-2 sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">教會位置</a></li>
    <li><a href="/location">教會位置</a></li>
  </ul>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">教會配置圖</a></li>
    <li><a href="/location/b1">地下室</a></li>
    <li><a href="/location/floor1">一樓</a></li>
    <li><a href="/location/floor2">二樓</a></li>
    <li><a href="/location/floor4">四樓</a></li>
    <li><a href="/location/floor5">五樓</a></li>
  </ul>
</div>

app/views/location/index.html.erb
<div class="container-fluid main-container">
  <%=render 'location/leftMenu' %>
  <div class="col-md-10 content">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>教會位置</h2>
        <img src="/images/floor/location.jpg" style="width:100%" alt="地圖"/>
        <h2>搭車訊息</h2>
        <h3>公車</h3>
        <ol>
          <li>
            <h4>埔墘站下，步行約7-10分鐘。(234、綠265、705)</h4>
          </li>
          <li>
            <h4>自來水廠站下，步行約3分鐘。（紅265)</h4>
          </li>
        </ol>
        <h3>捷運</h3>
        <ol>
          <li style="text-align: left;">
            <h4>新埔站（板南線）3號出口下車步行約15-20分鐘。</h4>
          </li>
          <li style="text-align: left;">
            <h4>新埔站（板南線）2號出口搭橘5，正隆廣場站下，步行約5分鐘。</h4>
          </li>
        </ol>
        <h3>開車</h3>
        <ol>
          <li>
            <h4>從光復橋下（板橋中山路）至三民路左轉直行至186巷右轉。</h4>
          </li>
          <li>
            <h4>從華江橋下，左轉雙十路二段，直行三民路至186巷右轉。</h4>
          </li>
          <li>
            <h4>國道三號中和交流道出口，往最內側中山路方向下交流道，直行至三民路右轉，再至186巷口左轉。</h4>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/news/index.html.erb
<% @news_list.each do |news| %>
    <li>
      <%= news.title %>|
      <%= news.content %>|
      <%= news.created_at.strftime('%Y%m%d') %>|
      <%= news.updated_at.strftime('%Y%m%d') %>|
      <%= news.key %>|
      <%= link_to "Show", news_path(news) %>
      <%= link_to 'Edit', edit_news_path(news) %>
      <%= button_to 'Delete', news_path(news), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </li>
<% end %>
</ul>

<%= link_to 'Add News', new_news_path %>

app/views/news/show.html.erb
show News
<%= @news.title %>
<%= simple_format(@news.content) %>

<p><%= link_to 'Back to index', :controller => 'news', :action => 'index' %></p>

app/views/page/about.html.erb
<h4>ABOUT PAGE</h4>
<%=@aboutwhat%>

app/views/page/contact.html.erb
<h4>CONTACT PAGE</h4>

app/views/witness/index.html.erb
<h3><i class="fa fa-plus-circle"></i>見証分享</h3>
<% if @is_admin %>
<%= link_to '+新的見証', new_witness_path %>
<% end %>
<hr/>
<div class="row">
  <% @witnesses.each do |witness| %>
      <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="<%=witness_path(witness)%>">
          <b><%= witness.title %></b>
        </a>
        <% if @is_admin %>
        <%= link_to '修改', edit_witness_path(witness), :class => "btn btn-sm btn-warning" %>
        <%= link_to '刪除', witness_path(witness), :class => "btn btn-sm btn-danger", :method => :delete, :data => { :confirm => "確定刪除?" } %>
        <% end %>
        <b><%=witness.created_at.strftime("%Y-%m-%d")%></b>
        <a href="<%=witness_path(witness)%>">

          <img src="<%= witness.photo %>" class="thumbnail img-responsive">
       </a>
      </div>
  <% end %>
</div>